# Generated by Django 4.2.5 on 2025-03-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
